AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  # amazonq-ignore-next-line
  MetricMigrationTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: metric_migrate_trigger/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 20
      Policies:
        - CloudWatchReadOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
      Environment:
        Variables:
          MIGRATION_QUEUE_URL: !Ref MetricMigrationQueue
      Events:
        MetricQuery:
          Type: Api
          Properties:
            Path: /migrate
            Method: post
  MetricMigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationQueue
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      # Enable dead-letter queue for failed migrations
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetricMigrationDLQ.Arn
        maxReceiveCount: 1
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # Dead Letter Queue for failed migrations
  MetricMigrationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationDLQ
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # amazonq-ignore-next-line
  MigrateMetricFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: migrate_metric/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MetricMigrationQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Timeout: 300  # 5 minutes
      MemorySize: 256
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Effect: Allow
            Action:
              - cloudwatch:*
            Resource: '*'
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: PrivateSubnetAId
          - Fn::ImportValue: PrivateSubnetBId
          - Fn::ImportValue: PrivateSubnetCId
      Environment:
        Variables:
          DB_HOST: !GetAtt MetricsDatabaseProxy.Endpoint
          DB_SECRET_NAME: !Ref MetricsDatabaseArchivistUserSecret
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: 
        Fn::ImportValue: VpcId
  MetricsDatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Metrics Database
      VpcId: 
        Fn::ImportValue: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref ProxySecurityGroup
    # Create a default target group for the proxy
  MetricsDatabaseProxyTargetGroup:
    Type: AWS::RDS::DBProxyTargetGroup
    Properties:
      DBProxyName: !Ref MetricsDatabaseProxy
      TargetGroupName: default
      DBClusterIdentifiers: 
        - !Ref MetricsDatabase
      ConnectionPoolConfigurationInfo:
        MaxConnectionsPercent: 100
        MaxIdleConnectionsPercent: 50
        ConnectionBorrowTimeout: 120
    DependsOn: MetricsDatabaseProxy
  MetricsDatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Metrics Database
      SubnetIds: 
        - Fn::ImportValue: PrivateSubnetAId
        - Fn::ImportValue: PrivateSubnetBId
        - Fn::ImportValue: PrivateSubnetCId
  MetricsDatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
  MetricsDatabaseArchivistUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: '{"username": "archivist"}'
        GenerateStringKey: "password"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
  MetricsDatabase:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: 15.3
      DatabaseName: metrics
      MasterUsername: !Sub '{{resolve:secretsmanager:${MetricsDatabaseSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${MetricsDatabaseSecret}:SecretString:password}}'
      ServerlessV2ScalingConfiguration:
        MinCapacity: 1  # Minimum ACU (Aurora Capacity Units)
        MaxCapacity: 16   # Maximum ACU
      VpcSecurityGroupIds: 
        - !Ref MetricsDatabaseSecurityGroup
      DBSubnetGroupName: !Ref MetricsDatabaseSubnetGroup
      Port: 5432
      EnableHttpEndpoint: true  # Enables Data API
      DeletionProtection: true
  MetricsDatabaseDefaultInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: aurora-postgresql
      DBInstanceClass: db.serverless
      DBClusterIdentifier: !Ref MetricsDatabase
      MonitoringInterval: 0

  MetricsDatabaseProxy:
    Type: AWS::RDS::DBProxy
    Properties:
      DBProxyName: !Sub ${AWS::StackName}-metrics-proxy
      EngineFamily: POSTGRESQL
      RoleArn: !GetAtt MetricsDatabaseProxyRole.Arn
      Auth:
        - AuthScheme: SECRETS
          SecretArn: !Ref MetricsDatabaseSecret
          IAMAuth: DISABLED
      VpcSubnetIds:
        - Fn::ImportValue: PrivateSubnetAId
        - Fn::ImportValue: PrivateSubnetBId
        - Fn::ImportValue: PrivateSubnetCId
      VpcSecurityGroupIds:
        - !Ref ProxySecurityGroup
      RequireTLS: true
      IdleClientTimeout: 1800
      DebugLogging: false
  MetricsDatabaseProxyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ProxySecretAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref MetricsDatabaseSecret
  ProxySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS Proxy
      VpcId: 
        Fn::ImportValue: VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
Outputs:
  MetricMigrationQueueUrl:
    Description: URL of the Metric Migration Queue
    Value: !Ref MetricMigrationQueue
  MetricMigrationQueueArn:
    Description: ARN of the Metric Migration Queue
    Value: !GetAtt MetricMigrationQueue.Arn
  MetricMigrationTriggerApi:
    Description: API Gateway endpoint URL for the metric migration trigger
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/migrate"