AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  MetricMigrationTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: metric_migrate_trigger/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 20
      Policies:
        - CloudWatchReadOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
      Environment:
        Variables:
          MIGRATION_QUEUE_URL: !Ref MetricMigrationQueue
      Events:
        MetricQuery:
          Type: Api
          Properties:
            Path: /migrate
            Method: post
  MetricMigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationQueue
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      # Enable dead-letter queue for failed migrations
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetricMigrationDLQ.Arn
        maxReceiveCount: 1
  # Dead Letter Queue for failed migrations
  MetricMigrationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationDLQ
      MessageRetentionPeriod: 1209600  # 14 days
  MigrateMetricFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: migrate_metric/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MetricMigrationQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Timeout: 300  # 5 minutes
      MemorySize: 256
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
        - CloudWatchLogsFullAccess
        - DynamoDBCrudPolicy:
            TableName: '*'  # Restrict to specific tables in production
        - CloudWatchPutMetricPolicy: {}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:*
              Resource: '*'  # You should restrict this to specific tables
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MetricMigrationQueueUrl:
    Description: URL of the Metric Migration Queue
    Value: !Ref MetricMigrationQueue
  MetricMigrationQueueArn:
    Description: ARN of the Metric Migration Queue
    Value: !GetAtt MetricMigrationQueue.Arn
  MetricMigrationTriggerApi:
    Description: API Gateway endpoint URL for the metric migration trigger
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/migrate"