AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam
Parameters:
    DataSourceName:
        Description: Data source name
        Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  # amazonq-ignore-next-line
  MetricMigrationTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: metric_migrate_trigger/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 20
      Policies:
        - CloudWatchReadOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
      Environment:
        Variables:
          MIGRATION_QUEUE_URL: !Ref MetricMigrationQueue
      Events:
        MetricQuery:
          Type: Api
          Properties:
            Path: /migrate
            Method: post
  MetricMigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationQueue
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      # Enable dead-letter queue for failed migrations
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetricMigrationDLQ.Arn
        maxReceiveCount: 1
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # Dead Letter Queue for failed migrations
  MetricMigrationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationDLQ
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # amazonq-ignore-next-line
  MigrateMetricFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: migrate_metric/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MetricMigrationQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Timeout: 300  # 5 minutes
      EphemeralStorage:
        Size: 5120
      MemorySize: 256
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Effect: Allow
            Action:
              - cloudwatch:*
            Resource: '*'
        - S3CrudPolicy:
            BucketName: !Ref ArchivedMetricsS3Bucket
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup
        SubnetIds:
          - Fn::ImportValue: PrivateSubnetAId
          - Fn::ImportValue: PrivateSubnetBId
          - Fn::ImportValue: PrivateSubnetCId
      Environment:
        Variables:
          ARCHIVED_METRICS_BUCKET_NAME: !Ref ArchivedMetricsS3Bucket
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: 
        Fn::ImportValue: VpcId
  ArchivedMetricsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain




  TimeshiftLambda:
      Type: AWS::Serverless::Function
      Properties:
        Runtime: python3.13
        Handler: app.lambda_handler
        CodeUri: timeshift/
        Description: "Lambda function for time-shifting operations"
        Tags:
          "cloudwatch:datasource": "s3-timeshifted"
        Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                Resource: "*"
  TimeshiftLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
          Action: lambda:InvokeFunction
          FunctionName:
              Ref: TimeshiftLambda
          Principal: lambda.datasource.cloudwatch.amazonaws.com
          SourceAccount:
              Ref: AWS::AccountId
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Description: A simple hello world function that includes random sleep time
      MemorySize: 128
      Timeout: 60  # Setting 60 seconds timeout due to the random sleep
Outputs:
  MetricMigrationQueueUrl:
    Description: URL of the Metric Migration Queue
    Value: !Ref MetricMigrationQueue
  MetricMigrationQueueArn:
    Description: ARN of the Metric Migration Queue
    Value: !GetAtt MetricMigrationQueue.Arn
  MetricMigrationTriggerApi:
    Description: API Gateway endpoint URL for the metric migration trigger
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/migrate"