AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  # amazonq-ignore-next-line
  MetricMigrationTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: metric_migrate_trigger/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 20
      Policies:
        - CloudWatchReadOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
      Environment:
        Variables:
          MIGRATION_QUEUE_URL: !Ref MetricMigrationQueue
      Events:
        MetricQuery:
          Type: Api
          Properties:
            Path: /migrate
            Method: post
  MetricMigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationQueue
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      # Enable dead-letter queue for failed migrations
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetricMigrationDLQ.Arn
        maxReceiveCount: 1
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # Dead Letter Queue for failed migrations
  MetricMigrationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationDLQ
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # amazonq-ignore-next-line
  MigrateMetricFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: migrate_metric/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MetricMigrationQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Timeout: 300  # 5 minutes
      MemorySize: 256
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
        - CloudWatchLogsFullAccess
        - DynamoDBCrudPolicy:
            TableName: '*'  # Restrict to specific tables in production
        - CloudWatchPutMetricPolicy: {}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:*
              Resource: '*'  # You should restrict this to specific tables
  MetricsTableBucket:
    # amazonq-ignore-next-line
    Type: AWS::S3Tables::TableBucket
    Properties:
      TableBucketName: !Sub 'metrics-table-bucket-${AWS::AccountId}'  # This ensures uniqueness
      UnreferencedFileRemoval:
        Status: Enabled
        NoncurrentDays: 7
        UnreferencedDays: 7
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  MetricsFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3TableAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: S3TableAccessViaGlueFederation
              Effect: Allow
              Action:
              - glue:GetTable
              - glue:GetDatabase
              - glue:UpdateTable
              Resource:
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog/s3tablescatalog/*'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog/s3tablescatalog'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*'
              - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*'
            - Sid: S3DeliveryErrorBucketPermission
              Effect: Allow
              Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
              Resource:
              - !GetAtt MetricFirehoseErrorBucket.Arn
              - !Sub '${MetricFirehoseErrorBucket.Arn}/*'
            - Sid: RequiredWhenDoingMetadataReadsANDDataAndMetadataWriteViaLakeformation
              Effect: Allow
              Action:
              - lakeformation:GetDataAccess
              Resource: "*"
            - Sid: LoggingInCloudWatch
              Effect: Allow
              Action:
              - logs:PutLogEvents
              Resource:
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:!Ref MetricFirehoseLogGroup:log-stream:*'
  MetricFirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: MetricFirehoseForS3TableBucket
      RetentionInDays: 14
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # amazonq-ignore-next-line
  MetricFirehoseErrorBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'metric-firehose-errors-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Id: ErrorLogRetention
            Status: Enabled
            ExpirationInDays: 90  # Adjust retention period as needed
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
Outputs:
  MetricMigrationQueueUrl:
    Description: URL of the Metric Migration Queue
    Value: !Ref MetricMigrationQueue
  MetricMigrationQueueArn:
    Description: ARN of the Metric Migration Queue
    Value: !GetAtt MetricMigrationQueue.Arn
  MetricMigrationTriggerApi:
    Description: API Gateway endpoint URL for the metric migration trigger
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/migrate"
  MetricsTableBucketArn:
      Description: ARN of the Metrics Table Bucket
      # amazonq-ignore-next-line
      Value: !GetAtt MetricsTableBucket.TableBucketARN