AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam
Parameters:
    DataSourceName:
        Description: Data source name
        Type: String
    S3CsvLoadingLambdaArn:
        Description: |
          ARN of the Lambda function that loads CSV data from S3 (created by CloudWatch S3 CSV Data Source setup).
          To get this ARN, follow the instructions at: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Metrics-Insights-datasources-S3.html
          After creating the S3 CSV Data Source in CloudWatch, find the Lambda ARN in the CloudWatch console under Data Sources.
        Type: String
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    AccessLogSetting:
      DestinationArn: !GetAtt ApiAccessLogGroup.Arn
      Format: '$context.requestId'
    MethodSettings:
      - ResourcePath: "/*"
        HttpMethod: "*"
        LoggingLevel: INFO
    Auth:
      ApiKeyRequired: true
Resources:
  # CloudWatch Logs group for API Gateway access logs
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/apigateway/${AWS::StackName}'
      RetentionInDays: 7
  # Dead Letter Queue for MetricMigrationTrigger failures
  MetricMigrationTriggerDLQ:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: "SQS encryption not needed for demo purposes."
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # amazonq-ignore-next-line
  MetricMigrationTrigger:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Lambda in VPC unneeded for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_117
            comment: "Lambda in VPC not needed for demo purposes."
          - id: CKV_AWS_173
            comment: "Environment variable encryption not needed for demo purposes."
    Properties:
      CodeUri: metric_migrate_trigger/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 20
      ReservedConcurrentExecutions: 100
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt MetricMigrationTriggerDLQ.Arn
      Policies:
        - CloudWatchFullAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationTriggerDLQ.QueueName
      Environment:
        Variables:
          MIGRATION_QUEUE_URL: !Ref MetricMigrationQueue
      Events:
        MetricQuery:
          Type: Api
          Properties:
            Path: /migrate
            Method: post
  MetricMigrationQueue:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: "SQS encryption not needed for demo purposes."
    Properties:
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      # Enable dead-letter queue for failed migrations
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetricMigrationDLQ.Arn
        maxReceiveCount: 1
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # Dead Letter Queue for failed migrations
  MetricMigrationDLQ:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: "SQS encryption not needed for demo purposes."
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # Dead Letter Queue for MigrateMetricFunction failures
  MigrateMetricFunctionDLQ:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: "SQS encryption not needed for demo purposes."
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # amazonq-ignore-next-line
  MigrateMetricFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Lambda in VPC unneeded for demo purposes."
          - id: W11
            reason: "CloudWatch ListMetrics, GetMetricData, and GetMetricStatistics do not support resource-level permissions. Wildcard is required and safe as these are read-only operations scoped to the account."
      checkov:
        skip:
          - id: CKV_AWS_117
            comment: "Lambda in VPC not needed for demo purposes."
          - id: CKV_AWS_173
            comment: "Environment variable encryption not needed for demo purposes."
    Properties:
      CodeUri: migrate_metric/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MetricMigrationQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Timeout: 300  # 5 minutes
      ReservedConcurrentExecutions: 10
      EphemeralStorage:
        Size: 5120
      MemorySize: 256
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt MigrateMetricFunctionDLQ.Arn
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MigrateMetricFunctionDLQ.QueueName
        - AWSLambdaBasicExecutionRole
        # CloudWatch metrics APIs do not support resource-level permissions
        # These read-only operations are safe with wildcard resource
        - Statement:
          - Effect: Allow
            Action:
              - cloudwatch:ListMetrics
              - cloudwatch:GetMetricData
              - cloudwatch:GetMetricStatistics
            Resource: '*'
        - S3CrudPolicy:
            BucketName: !Ref ArchivedMetricsS3Bucket
      Environment:
        Variables:
          ARCHIVED_METRICS_BUCKET_NAME: !Ref ArchivedMetricsS3Bucket
  ArchivedMetricsS3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "Bucket access logging not needed for demo purposes."
          - id: W51
            reason: "Bucket policy not needed for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_18
            comment: "S3 bucket access logging not needed for demo purposes."
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # Dead Letter Queue for TimeshiftLambda failures
  TimeshiftLambdaDLQ:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: "SQS encryption not needed for demo purposes."
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  TimeshiftLambda:
      Type: AWS::Serverless::Function
      Metadata:
        cfn_nag:
          rules_to_suppress:
            - id: W89
              reason: "Lambda in VPC unneeded for demo purposes."
        checkov:
          skip:
            - id: CKV_AWS_117
              comment: "Lambda in VPC not needed for demo purposes."
            - id: CKV_AWS_173
              comment: "Environment variable encryption not needed for demo purposes."
      Properties:
        Runtime: python3.13
        Handler: app.lambda_handler
        CodeUri: timeshift/
        Description: "Lambda function for time-shifting operations"
        ReservedConcurrentExecutions: 50
        DeadLetterQueue:
          Type: SQS
          TargetArn: !GetAtt TimeshiftLambdaDLQ.Arn
        Tags:
          "cloudwatch:datasource": "s3-timeshifted"
        Environment:
          Variables:
            S3_CSV_LOADING_LAMBDA_ARN: !Ref S3CsvLoadingLambdaArn
        Policies:
          - SQSSendMessagePolicy:
              QueueName: !GetAtt TimeshiftLambdaDLQ.QueueName
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                Resource: !Ref S3CsvLoadingLambdaArn
  TimeshiftLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
          Action: lambda:InvokeFunction
          FunctionName:
              Ref: TimeshiftLambda
          Principal: lambda.datasource.cloudwatch.amazonaws.com
          SourceAccount:
              Ref: AWS::AccountId
  # Dead Letter Queue for HelloWorldFunction failures
  HelloWorldFunctionDLQ:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_27
            comment: "SQS encryption not needed for demo purposes."
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Lambda in VPC unneeded for demo purposes."
      checkov:
        skip:
          - id: CKV_AWS_117
            comment: "Lambda in VPC not needed for demo purposes."
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      ReservedConcurrentExecutions: 500
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt HelloWorldFunctionDLQ.Arn
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt HelloWorldFunctionDLQ.QueueName
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  ServerlessRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ServerlessRestApi
      Description: !Sub "Deployment for ${AWS::StackName}"
  
  # API Key and Usage Plan Resources
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: ServerlessRestApiProdStage
    Properties:
      Name: !Sub "${AWS::StackName}-api-key"
      Enabled: true
  
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ServerlessRestApiProdStage
    Properties:
      UsagePlanName: !Sub "${AWS::StackName}-usage-plan"
      ApiStages:
        - ApiId: !Ref ServerlessRestApi
          Stage: Prod
      Quota:
        Limit: 10000
        Period: DAY
      Throttle:
        BurstLimit: 200
        RateLimit: 100
  
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan
Outputs:
  MetricMigrationQueueUrl:
    Description: URL of the Metric Migration Queue
    Value: !Ref MetricMigrationQueue
  MetricMigrationQueueArn:
    Description: ARN of the Metric Migration Queue
    Value: !GetAtt MetricMigrationQueue.Arn
  MetricMigrationTriggerApi:
    Description: API Gateway endpoint URL for the metric migration trigger
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/migrate"
  HelloWorldApi:
    Description: API Gateway endpoint URL for HelloWorld function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
    Export:
      Name: !Sub "${AWS::StackName}-HelloWorldApiUrl"
  ApiKeyId:
    Description: API Key ID (use AWS CLI to get the actual key value)
    Value: !Ref ApiKey
  GetApiKeyCommand:
    Description: Command to retrieve your API key
    Value: !Sub "aws apigateway get-api-key --api-key ${ApiKey} --include-value --query 'value' --output text"