AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam
Parameters:
    DataSourceName:
        Description: Data source name
        Type: String
    S3CsvLoadingLambdaArn:
        Description: |
          ARN of the Lambda function that loads CSV data from S3 (created by CloudWatch S3 CSV Data Source setup).
          To get this ARN, follow the instructions at: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Metrics-Insights-datasources-S3.html
          After creating the S3 CSV Data Source in CloudWatch, find the Lambda ARN in the CloudWatch console under Data Sources.
        Type: String
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W68
            reason: "Usage Plan not needed for demo purposes."
          - id: W69
            reason: "No Access Logs needed for demo purposes."
Resources:
  # amazonq-ignore-next-line
  MetricMigrationTrigger:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Lambda in VPC unneeded for demo purposes."
    Properties:
      CodeUri: metric_migrate_trigger/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 20
      ReservedConcurrentExecutions: 100
      Policies:
        - CloudWatchFullAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
      Environment:
        Variables:
          MIGRATION_QUEUE_URL: !Ref MetricMigrationQueue
      Events:
        MetricQuery:
          Type: Api
          Properties:
            Path: /migrate
            Method: post
  MetricMigrationQueue:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
    Properties:
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      # Enable dead-letter queue for failed migrations
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetricMigrationDLQ.Arn
        maxReceiveCount: 1
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # Dead Letter Queue for failed migrations
  MetricMigrationDLQ:
    Type: AWS::SQS::Queue
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W48
            reason: "Customer Master Keys (CMKs) not needed for demo purposes."
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  # amazonq-ignore-next-line
  MigrateMetricFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Lambda in VPC unneeded for demo purposes."
          - id: W11
            reason: "CloudWatch ListMetrics, GetMetricData, and GetMetricStatistics do not support resource-level permissions. Wildcard is required and safe as these are read-only operations scoped to the account."
    Properties:
      CodeUri: migrate_metric/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MetricMigrationQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Timeout: 300  # 5 minutes
      ReservedConcurrentExecutions: 10
      EphemeralStorage:
        Size: 5120
      MemorySize: 256
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
        - AWSLambdaBasicExecutionRole
        # CloudWatch metrics APIs do not support resource-level permissions
        # These read-only operations are safe with wildcard resource
        - Statement:
          - Effect: Allow
            Action:
              - cloudwatch:ListMetrics
              - cloudwatch:GetMetricData
              - cloudwatch:GetMetricStatistics
            Resource: '*'
        - S3CrudPolicy:
            BucketName: !Ref ArchivedMetricsS3Bucket
      Environment:
        Variables:
          ARCHIVED_METRICS_BUCKET_NAME: !Ref ArchivedMetricsS3Bucket
  ArchivedMetricsS3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "Bucket access logging not needed for demo purposes."
          - id: W51
            reason: "Bucket policy not needed for demo purposes."
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  TimeshiftLambda:
      Type: AWS::Serverless::Function
      Metadata:
        cfn_nag:
          rules_to_suppress:
            - id: W89
              reason: "Lambda in VPC unneeded for demo purposes."
      Properties:
        Runtime: python3.13
        Handler: app.lambda_handler
        CodeUri: timeshift/
        Description: "Lambda function for time-shifting operations"
        ReservedConcurrentExecutions: 50
        Tags:
          "cloudwatch:datasource": "s3-timeshifted"
        Environment:
          Variables:
            S3_CSV_LOADING_LAMBDA_ARN: !Ref S3CsvLoadingLambdaArn
        Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                Resource: !Ref S3CsvLoadingLambdaArn
  TimeshiftLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
          Action: lambda:InvokeFunction
          FunctionName:
              Ref: TimeshiftLambda
          Principal: lambda.datasource.cloudwatch.amazonaws.com
          SourceAccount:
              Ref: AWS::AccountId
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: "Lambda in VPC unneeded for demo purposes."
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      ReservedConcurrentExecutions: 500
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  ServerlessRestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W68
            reason: "Usage Plan not needed for demo purposes."
          - id: W69
            reason: "Access Logs not needed for demo purposes."
          - id: W64
            reason: "Usage Plan not needed for demo purposes."
Outputs:
  MetricMigrationQueueUrl:
    Description: URL of the Metric Migration Queue
    Value: !Ref MetricMigrationQueue
  MetricMigrationQueueArn:
    Description: ARN of the Metric Migration Queue
    Value: !GetAtt MetricMigrationQueue.Arn
  MetricMigrationTriggerApi:
    Description: API Gateway endpoint URL for the metric migration trigger
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/migrate"
  HelloWorldApi:
    Description: API Gateway endpoint URL for HelloWorld function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
    Export:
      Name: !Sub "${AWS::StackName}-HelloWorldApiUrl"