AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  MetricMigrationTrigger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: metric_migrate_trigger/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 30
      Policies:
        - CloudWatchReadOnlyAccess
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetricMigrationQueue.QueueName
      Environment:
        Variables:
          MIGRATION_QUEUE_URL: !Ref MetricMigrationQueue
      Events:
        MetricQuery:
          Type: Api
          Properties:
            Path: /migrate
            Method: post
  MetricMigrationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationQueue
      VisibilityTimeout: 300  # 5 minutes
      MessageRetentionPeriod: 1209600  # 14 days
      # Enable dead-letter queue for failed migrations
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt MetricMigrationDLQ.Arn
        maxReceiveCount: 3
  # Dead Letter Queue for failed migrations
  MetricMigrationDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MetricMigrationDLQ
      MessageRetentionPeriod: 1209600  # 14 days
  SQSToStepFunctionPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Name: SQSToStepFunctionPipe
      RoleArn: !GetAtt PipeRole.Arn
      Source: !GetAtt MetricMigrationQueue.Arn
      Target: !Ref MetricMigrationStateMachine
      TargetParameters:
        StepFunctionStateMachineParameters:
          InvocationType: FIRE_AND_FORGET
      SourceParameters:
        SqsQueueParameters:
          BatchSize: 1
      LogConfiguration:
        Level: TRACE
        CloudwatchLogsLogDestination:
          LogGroupArn: !GetAtt PipeLogGroup.Arn
  PipeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/pipes/SQSToStepFunctionPipe'
      RetentionInDays: 14
  PipeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: pipes.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt MetricMigrationQueue.Arn
        - PolicyName: StepFunctionsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:*
                Resource: '*'
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/pipes/SQSToStepFunctionPipe:*'

  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/stepfunctions/MetricMigrationStateMachine'
      RetentionInDays: 14

  StateMachineLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutLogEvents
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: '*'
  MetricMigrationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: MetricMigrationStateMachine
      Type: STANDARD
      DefinitionUri: statemachines/metric_migration.asl.yaml
      DefinitionSubstitutions:
        MigrateMetricFunctionArn: !GetAtt MigrateMetricFunction.Arn
      Policies:
        - CloudWatchLogsFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: '*'  # You should restrict this to specific tables
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt MigrateMetricFunction.Arn
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: true
        Level: ALL
  MigrateMetricFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: migrate_metric/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
        - x86_64
      Timeout: 300  # 5 minutes
      MemorySize: 256
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'  # Restrict to specific tables in production
        - CloudWatchPutMetricPolicy: {}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:*
              Resource: '*'  # You should restrict this to specific tables

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
  MetricMigrationQueueUrl:
    Description: URL of the Metric Migration Queue
    Value: !Ref MetricMigrationQueue
  MetricMigrationQueueArn:
    Description: ARN of the Metric Migration Queue
    Value: !GetAtt MetricMigrationQueue.Arn
  MetricMigrationTriggerApi:
    Description: API Gateway endpoint URL for the metric migration trigger
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/migrate"